package ClassExcerises.Exercises;

public class haiku {
    public static void main (String[] args){
        System.out.print ("Steely gaze, power,\n" +
                "Putin's rule, strong and profound,\n" +
                "Russia's fate he wields.");
    }
}
/*
 Generated by chat gpt.
 Back slash n '\n' makes the text go onto the next line.
 Plus '+' concatenates the text.
 Backslash '\t' makes a new tab.
 Backslash '\" text \"' will generate literal quotes.
 Double backslash will show a single backslash: '\\' = '\'.
 \b creates a backspace, deleting the preceding character when the code is run.
 Example: 'System.out.print("Hello\bWorld");' = HellWorld
*/
